// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package case_study_1.RawSensorReading

object RawSensorReadingProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      case_study_1.RawSensorReading.RawSensorReading
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChZSYXdTZW5zb3JSZWFkaW5nLnByb3RvEgxjYXNlX3N0dWR5XzEiygEKEFJhd1NlbnNvclJlYWRpbmcSKQoIc2Vuc29ySWQYA
  SABKAlCDeI/ChIIc2Vuc29ySWRSCHNlbnNvcklkEiwKCXRpbWVzdGFtcBgCIAEoA0IO4j8LEgl0aW1lc3RhbXBSCXRpbWVzdGFtc
  BIyCgt0ZW1wZXJhdHVyZRgDIAEoAkIQ4j8NEgt0ZW1wZXJhdHVyZVILdGVtcGVyYXR1cmUSKQoIaHVtaWRpdHkYBCABKAJCDeI/C
  hIIaHVtaWRpdHlSCGh1bWlkaXR5YgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}