// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package case_study_1.AggregatedSensorMetrics

object AggregatedSensorMetricsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      case_study_1.AggregatedSensorMetrics.AggregatedSensorMetrics
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch1BZ2dyZWdhdGVkU2Vuc29yTWV0cmljcy5wcm90bxIMY2FzZV9zdHVkeV8xIsUDChdBZ2dyZWdhdGVkU2Vuc29yTWV0cmljc
  xIpCghzZW5zb3JJZBgBIAEoCUIN4j8KEghzZW5zb3JJZFIIc2Vuc29ySWQSOwoOYXZnVGVtcGVyYXR1cmUYAiABKAJCE+I/EBIOY
  XZnVGVtcGVyYXR1cmVSDmF2Z1RlbXBlcmF0dXJlEjIKC2F2Z0h1bWlkaXR5GAMgASgCQhDiPw0SC2F2Z0h1bWlkaXR5UgthdmdId
  W1pZGl0eRI7Cg5taW5UZW1wZXJhdHVyZRgEIAEoAkIT4j8QEg5taW5UZW1wZXJhdHVyZVIObWluVGVtcGVyYXR1cmUSOwoObWF4V
  GVtcGVyYXR1cmUYBSABKAJCE+I/EBIObWF4VGVtcGVyYXR1cmVSDm1heFRlbXBlcmF0dXJlEjIKC21pbkh1bWlkaXR5GAYgASgCQ
  hDiPw0SC21pbkh1bWlkaXR5UgttaW5IdW1pZGl0eRIyCgttYXhIdW1pZGl0eRgHIAEoAkIQ4j8NEgttYXhIdW1pZGl0eVILbWF4S
  HVtaWRpdHkSLAoJZGF0YUNvdW50GAggASgFQg7iPwsSCWRhdGFDb3VudFIJZGF0YUNvdW50YgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}